### PR TITLE
Feature/html open progress

### PR DESCRIPTION
**Pull request by maverickg**
Use an html file to include Stan's progress text file, so we can just call `utils::browseURL`.

For now, it's only tested on mac.

### CODE REVIEW

**Comment by maverickg** [comment]
this works on windows too.

**Comment by maverickg** [comment]
@bgoodri can you check if it works on Linux.  I don't have a Linux around now.

**Comment by bgoodri** [comment]
Yes, this works for me on Linux. Do you know what it does in RStudio for Windows? I had assumed that stdout would be mapped to the RStudio console but apparently not. If so, then we should probably have open_progress default to `TRUE` on Windows.

**Comment by maverickg** [comment]
I don't find rstudio on windows is different from what we would expect in terms of the standard output: when mc.cores is not set, I can still see the stdout from RStudio.  

However, RStudio open the html file a bit different R-Gui.  For now, this fails for RStudio.  I still need to see if I can make it work for RStudio too. It does not open the html file as a local file. Instead, it uses something like `http://localhost:12332/session/filed9c12231e7a_StanProgress.html`, which cannot show the text file that is included.

**Comment by bgoodri** [comment]
OK. It would be good if we can get it to work on RStudio. But just to clarify, if `mc.cores > 1`, then you do not see stdout in the RStudio console like there is for Linux / Mac?

**Comment by maverickg** [comment]
It turns out the current code does not work for rstudio on mac either. Rstudio's has a function for option browser, which does not handle this case correctly.  So I am surprised that it works on Rstudio for Linux. 

```
# in RStudio
> getOption('browser')
function (url) 
{
    .Call(.rs.routines$rs_browseURL, url)
}
<environment: 0x1018ba630>
```

So if it's rstudio, I am gonna set browser to /usr/bin/open for mac, NULL for windows.  Is there a value to set for Linux? 

Yes, at least it had happened for me that if `mc.cores > 1`, I do not see stdout in the RStudio console like there is for Mac.

eeek, rstudio.  ok, i am done with this.

**Comment by bgoodri** [comment]
It plain R for Linux,

> getOption("browser")
> [1] "xdg-open"

Ben

**Comment by bgoodri** [comment]
Can you open the local URL in the RStudio viewer?

https://support.rstudio.com/hc/en-us/articles/202133558-Extending-RStudio-with-the-Viewer-Pane

**Comment by bgoodri** [comment]
Does 5048306 work for you on Mac and Windows in RStudio when `mc.cores > 1`?

**Comment by maverickg** [comment]
For some reason, rstudio just hangs there after https://github.com/stan-dev/rstan/commit/50483065b03f76a262fc5923d9c8149f39df6bf6.  In fact, this happened too before if I am using utils::browseURL in rstudio on mac for which rstudio sets its browser option.

**Comment by bgoodri** [comment]
What about 6ad5fad?

**Comment by maverickg** [comment]
That works well on windows.  I could test it on mac tonight, but it should work unless there is another bug in rstudio.

**Comment by maverickg** [comment]
It still hangs there.  After I clicked stop in rstudio, I can see some output from the text file.  I am enclosing an screenshot below. 

rstudio error

**Comment by bgoodri** [comment]
So, are you saying it does not hang on Windows if cores > 1? That would be
adequate for now because sending stdout to the console works well in
RStudio on Mac / Linux.

**Comment by maverickg** [comment]
It does not hang for me on Windows.

**Pull request merged**
