### PR TITLE
loo method for stanfit objects (loo.stanfit)

### PR DESCRIPTION
**Pull request by jgabry**
#### Summary:

This PR adds a `loo.stanfit` method. 

Note: can be merged once __loo__ v2.0.0 is on CRAN (already submitted but not published yet). 

#### Intended Effect:

Unlike the `loo.stanreg` method in __rstanarm__, for __rstan__ we can't automatically compute the pointwise log-likelihood, but we can still provide a convenient wrapper for the functions in the __loo__ package. 

The `loo.stanfit` method extracts the draws of the transformed parameter or generated quantity that the user indicates corresponds to the pointwise log-likelihood, computes `loo::relative_eff()` to use as the `r_eff` argument (new in __loo__ 2.0.0), and then calls `loo::loo.array`. 

#### How to Verify:

Run the examples in the doc. Copying here:

```r
stopifnot(packageVersion("loo") >= 2.0.0)
# Generate a dataset from N(0,1)
N <- 100
y <- rnorm(N, 0, 1)

# Suppose we have three models for y: 
#  1) y ~ N(-1, sigma) 
#  2) y ~ N(0.5, sigma)
#  3) y ~ N(0.6,sigma)
# 
stan_code <- "
data {
  int N;
  vector[N] y;
  real mu_fixed;
}
parameters {
  real<lower=0> sigma;
}
model { 
  sigma ~ exponential(1);
  y ~ normal(mu_fixed, sigma);
}
generated quantities {
  vector[N] log_lik;
  for (n in 1:N) log_lik[n] = normal_lpdf(y[n]| mu_fixed, sigma);
}"

mod <- stan_model(model_code = stan_code)
fit1 <- sampling(mod, data=list(N=N, y=y, mu_fixed=-1))
fit2 <- sampling(mod, data=list(N=N, y=y, mu_fixed=0.5))
fit3 <- sampling(mod, data=list(N=N, y=y, mu_fixed=0.6))

# use the loo method for stanfit objects
loo1 <- loo(fit1, pars = "log_lik")
print(loo1)

# which is equivalent to 
LL <- as.array(fit1, pars = "log_lik")
r_eff <- loo::relative_eff(exp(LL))
loo1b <- loo::loo.array(LL, r_eff = r_eff)
print(loo1b)

# compute loo for the other models
loo2 <- loo(fit2)
loo3 <- loo(fit3)

# stacking weights
wts <- loo::loo_model_weights(list(loo1, loo2, loo3), method = "stacking")
print(wts)
```

#### Documentation:

Install and see new doc at `help("loo.stanfit")`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by avehtari** [comment]
Looks great! I didn't have time to test yet (I can test tomorrow)

**Review by avehtari — APPROVED** [review]
I tested the new function with rstan Kilpisjärvi temperature models and it works fine. Very nice!

**Comment by jgabry** [comment]
With __loo__ 2.0.0 now on CRAN this can get merged whenever. @bgoodri I assume you're ok with us adding the `loo.stanfit` method?

**Comment by bgoodri** [comment]
Sure

**Pull request merged**
