### PR TITLE
Speed up and simplify read_stan_csv()

### PR DESCRIPTION
**Pull request by mespe**
#### Summary:

Simplify and speeds up `read_stan_csv()` without requiring any additional imports beyond `utils::read.csv()`

#### Intended Effect:

In my testing, results in a 2x faster reading of cmdstan CSV files, while also significantly clarifying the code in `read_stan_csv()`. Comparison to results from rstan:develop using `all.equal()` only differ by the permutations slot, which is expected.

Additionally, simplifies the code in `get_time_from_csv()` to a single `gsub()` operation per time.

#### How to Verify:

Compare to `stanfit` object created from rstan:develop's `read_stan_csv()` using `all.equal()`.
 
#### Side Effects:

Adds import of `read.csv()` from pkg:utils

#### Documentation:

None needed

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mespe** [comment]
FYI, passes `R CMD check --as-cran` with no ERRORs or WARNINGS on my machine - seems the CI systems need to be tweaked.

**Comment by bgoodri** [comment]
This looks fine to me. @aaronjg or @maverickg do you remember what the original reason was for using `scan` rather than `read.csv`?

**Comment by aaronjg** [comment]
This speed up is very impressive. I was trying to remember why I didn't go this route in my speed improvements, which is much more complicated.

Perhaps I wasn't aware of the textConnection function, and needed a way to handle the comments?

If this gets all the data that are needed from the comments, and the lp__ info in the header, than this is a great improvement.

**Comment by mespe** [comment]
If speed is a concern here, there are other optimizations that can be done - read.csv() is slow. 

A hybrid of an approach using scan() and mine which avoids looping over individual lines would probably be faster than my PR. I did not optimize this heavily. I was mostly concerned with getting a speed up with easy to understand/simple code.

**Comment by SteveBronder** [comment]
fyi for those who also didn't see in #843 this fixes a lil' bug on 32 bit windows for our CI! `scan()` was doing something odd for windows

**Comment by jgabry** [comment]
This is great (thanks @mespe!), although I think at some point we should retire `read_stan_csv()`. I think the function `read_cmdstan_csv()` that @rok-cesnovar wrote for the CmdStanR interface should be much faster than this and there's really no need for RStan to offer CmdStan tools anymore now that CmdStanR exists (rstan::stan_rdump() can also be retired because `cmdstanr::write_stan_json()` is easier to use and JSON IO is _much_ faster for CmdStan so no need to use the Rdump format ever again). Of course for backwards compatibility we should keep it and I'm all for these speed improvements, but I don't think this function needs to be kept around in the long term.

**Comment by SteveBronder** [comment]
@jgabry or @bgoodri do one of yinz have time to review this? I would but idt I have approval rights in the repo

**Comment by wds15** [comment]
@jgabry as I recall, the `read_cmdstan_csv` outputs `cmdstanr` objects rather than a `stanfit` thing. In my programs I still rely on the `extract` list output, which I don't get from the `posterior` style objects. Or did I miss something there?

**Comment by jgabry** [comment]
Yeah you're totally right. For `cmdstanr::read_cmdstan_csv()` to fully replace `rstan::read_stan_csv()` we'll need to be able to offer that additional functionality in the posterior package. We don't have that yet but the work is in progress. So for now there's definitely still a use case for `rstan::read_stan_csv()`, but eventually we should be able to replace it.

**Pull request merged**
