### PR TITLE
Cleanup C++ a bit

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary:

This does a few small things

1. The callbacks had getters `const auto& blah() const {}` but not setters `auto& blah() {}`. This made `rstan` use `const_cast<>()` in a few places. Modifying const variables, even with a const cast is still UB (I'm pretty sure). I also modified the functions that took in an `const Rcpp::List&` and did a const cast to just have an input argument of `Rcpp::List&`

2. There's a few places where things could be `const&` but were copying instead so I made them `const&`

3. `sample_writer_factory(...)` now returns a `unique_ptr`. Then when resetting the pointer the factory is assigned to we do `ptr.reset(sample_writer_factory(...).release())`

4. I have Qs about [this early return after resetting `idx`](https://github.com/stan-dev/rstan/compare/cleanup/const-accessors?expand=1#diff-6f71230a3e987d03fdf2763abf502967R125), should that first do the early return check first and then reset idx? I also wasn't sure about the column major loop [here](https://github.com/stan-dev/rstan/compare/cleanup/const-accessors?expand=1#diff-6f71230a3e987d03fdf2763abf502967R132)

5. Used C++11 auto iterators instead of looping with the pointer like

```cpp
    // before
    for (typename std::vector<std::vector<T> >::const_iterator it = idx.begin();
         it != idx.end();
         ++it) {
   // now
    for (auto&& it : idx) {
```

6. Should `upar` in the below be a `const&`? Would save a copy if that's fine

```cpp
Rcpp::NumericVector stan_fit::log_prob(std::vector<double> upar,
```

There's a good few functions/methods like that I can change

Also my IDE removes extra spaces when I save a file so sorry there's a bunch of weird white space deletions

#### Intended Effect:

Trying to fixup things a bit

#### How to Verify:

`make check`

#### Side Effects:

Hopefully none

#### Documentation:

Do you want me to add any docs here?

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Gonna let @bgoodri review this one, but thanks @SteveBronder!

**Comment by jgabry** [comment]
@SteveBronder @bgoodri looks like this is still open from July. Are we waiting on something to merge this or was there a decision not to make these changes?

**Comment by SteveBronder** [comment]
Oh I think it needs updated. @bgoodri if you think this is unnecessary though feel free to close it

**Comment by jgabry** [comment]
I was just going through and looking into PRs that have been open for a while. Fine to keep this open if it needs updating.

**Pull request closed without merging**
