### PR TITLE
CSV speed improvements and support for large CSV files

### PR DESCRIPTION
**Pull request by aaronjg**
#### Summary:

Read in CSVs line by line so that CSV files with more than
INT_MAX entries can be supported properly, since base R's
scan function does not have long vector support.

This is also saves more performant since we can preallocate
the data.frame, and fill it in row by row, rather than
reading in the entire CSV, converting it into a matrix,
and then into a data.frame. We also read the comment lines
and data lines in one pass through the file rather than
separate passes.

#### Intended Effect:

Fix limit on read_stan_csv (https://github.com/stan-dev/rstan/issues/530) without requiring a patch to base R. 

#### Side Effects:

Faster to read in CSV files even when they do not exceed the max size limit.

#### How to Verify:

Create large file via CMDStan and read in with read_stan_csv. 
Reading 100 iterations from the following model:
```
parameters {
  vector[10000] theta;
} 
model {
  target += -0.5*dot_self(theta);
}
```

Old:
> system.time(x <- read_stan_csv("output.csv"))
   user  system elapsed 
  3.333   0.056   5.191

New:
> system.time(x <- read_stan_csv("output.csv"))
   user  system elapsed 
  2.148   0.049   3.409 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Aaron Goodman

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by aaronjg** [comment]
My patch was applied to base R (https://github.com/wch/r-source/commit/86f7ea9c53eba1b68e9e0206db4c4f8dd3b24dd4)  so the root cause is fixed. However, this PR is still a speed improvement, and reduces the number of times the sample data frame must be copied in memory so you are not required to have 2X+ the available RAM to load in the sample file.

**Comment by aaronjg** [comment]
It looks like this is hitting a corner case in the R-3.5.0's new file buffering from https://github.com/wch/r-source/commit/72d40085f57c325f7f3dac67f75fd4b2ebf34c48. I filed a bug report with R-devel, but this shouldn't be merged in until the next patch release of R.

**Comment by aaronjg** [comment]
I added a work around for newer versions of R, so this new CSV reading also works on R >= 3.5.0.

**Comment by bgoodri** [comment]
@aaronjg When I merged this, it was passing the tests, but a bunch of things got messed up subsequently. I tried to fix everything, but now it seems that the example and tests for `read_stan_csv` is failing on develop with the message "Error in row.buffer[buffer.pointer, ] <- scan(con, nlines = 1, sep = ",",  :  replacement has length zero". Can you take a look at it and let me know what I need to do to fix it? Sorry.

**Comment by aaronjg** [comment]
Sure. Where are the test cases that are failing? I looked at "./rstan/example/testreadcsv.R" but that seems to be somewhat out of date.

**Comment by bgoodri** [comment]
Just example(read_stan_csv)

**Comment by aaronjg** [comment]
There was an extra LF at the end of the example csv. I don't think Stan generates those CSVs with extra LF now, but I am handling it just in case.

Fixed with commit 1c3236ec

**Comment by bgoodri** [comment]
OK. Thanks!

**Pull request merged**
