### PR TITLE
add moment matching option for loo.stanfit

### PR DESCRIPTION
**Pull request by topipa**
#### Summary:

This PR adds moment matching functionality to `loo.stanfit`

Default behaviour of `loo.stanfit` does not change, but by setting the argument `moment_match` to `TRUE`, moment matching correction is done for observations with pareto k values over `k_threshold`.

I am adding this PR now, but because these changes depend on recent changes in the loo package (https://github.com/stan-dev/loo/pull/130), merging may have to wait depending on which package is updated to CRAN first.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Topi Paananen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by paul-buerkner — APPROVED** [review]
The PR looks good to me.

**Comment by bgoodri** [comment]
Do we just need a loo release to CRAN in order to merge this? @topipa @jgabry

**Comment by jgabry** [comment]
Unless @topipa needs/wants to change anything then yeah all we need is a loo release.

**Comment by bgoodri** [comment]
All the naming conventions got worked out?

**Comment by jgabry** [comment]
Yeah, we're going with the current conventions on the loo master branch. From what I can tell those are consistent with this PR but @topipa can you confirm? 

(@topipa I'm in the process of releasing loo, so we want to merge this and release it with the next rstan, which is going out ASAP.)

**Comment by topipa** [comment]
I tested these changes against the current loo master branch, and everything seemed to work. The only thing I changed is I updated the moment matching reference in the documentation. So the PR seems to be okay for merging.

**Comment by jgabry** [comment]
Ok thanks @topipa!

**Pull request merged**
