### PR TITLE
Add basic Jenkinsfile

### PR DESCRIPTION
**Pull request by seantalts**
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
@seantalts Why does the Mac not have write permissions to install packages?

**Comment by seantalts** [comment]
As which user?

**Comment by bgoodri** [comment]
Whoever this is

http://d1m1s1b1.stat.columbia.edu:8080/job/RStan%20Pipeline/job/PR-463/7/console

**Comment by seantalts** [comment]
Ah, I bet the Jenkins user isn't an admin (which is good for security). Can
you install R packages locally for a user?

**Comment by bgoodri** [comment]
I think if you are logged in on that machine as the Jenkins user, start R
interactively, and try to install a package like devtools, it will ask you
if you want to create a directory to install packages under $HOME.

**Comment by sakrejda** [comment]
@seantalts Narrow answer: yes you can, and you can pick where you install: 

here's an example: https://github.com/sakrejda/tooling, check out the R-libraries.txt file and the packages.R file.  

From bash you can also do this: R CMD INSTALL package_1.0.tar.gz --library=${R_LIB_DIR}

From bash you can run scripts to reference that library:
```
R_LIBS_USER=${R_LIB_DIR}" Rscript my-r-script.R
```

From an R script you can switch libraries with: `.libPaths("R/library")`

**Comment by bgoodri** [comment]
Jenkins, retest this please.

**Comment by seantalts** [comment]
The comments don't work for new pipeline builds.

Also we could just install the R packages on a machine and restrict the builds to that machine?

**Comment by bgoodri** [comment]
Jenkins, test this please.

**Review by bgoodri — APPROVED** [review]
This should be fine now that Math is fixed.

**Pull request merged**
