### PR TITLE
Stan's refactor

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:
This goes along with Stan's refactor. This updates RStan so it's compatible with the changes to Stan.

Do not merge until stan-dev/stan#1751 is fixed.

#### Intended Effect:
Updates RStan.

#### How to Verify:
Build a new version of RStan:
```
R CMD build StanHeaders/
R CMD INSTALL StanHeaders_*.tar.gz
cd rstan
make build && make install
```

Run this from R (it goes through the 19 different ways to run different algorithms):
```R
library(rstan)
## options(mc.cores = parallel::detectCores())
fit <- stan(model_code = "transformed data { int N; int n; N = 10; n = 3; } parameters { real<lower = 0, upper = 1> theta; } model { n ~ binomial(N, theta); }")
fit
get_inits(fit)

## 1. diagnose:
fit <- stan(fit = fit, test_grad = TRUE)

## 2: optimize newton
optimizing(get_stanmodel(fit), algorithm = "Newton")

## 3: optimize bfgs
optimizing(get_stanmodel(fit), algorithm = "BFGS")

## 4: optimize lbfgs
optimizing(get_stanmodel(fit), algorithm = "LBFGS")
                               
## 5: sample fixed_param
fit <- stan(fit = fit, algorithm = "Fixed_param")

## 6: sample nuts dense_e adapt_false
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "dense_e", adapt_engaged = FALSE))

## 7: sample nuts dense_e adapt_true
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "dense_e", adapt_engaged = TRUE))

## 8: sample nuts diag_e adapt_false
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "diag_e", adapt_engaged = FALSE))

## 9: sample nuts diag_e adapt_true
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "diag_e", adapt_engaged = TRUE))

## 10: sample nuts unit_e adapt_false
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "unit_e", adapt_engaged = FALSE))

## 11: sample nuts unit_e adapt_true
fit <- stan(fit = fit, algorithm = "NUTS", control = list(metric = "unit_e", adapt_engaged = TRUE))

## 12: sample static dense_e adapt_false
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "dense_e", adapt_engaged = FALSE))

## 13: sample static dense_e adapt_true
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "dense_e", adapt_engaged = TRUE))

## 14: sample static diag_e adapt_false
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "diag_e", adapt_engaged = FALSE))

## 15: sample static diag_e adapt_true
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "diag_e", adapt_engaged = TRUE))

## 16: sample static unit_e adapt_false
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "unit_e", adapt_engaged = FALSE))

## 17: sample static unit_e adapt_true
fit <- stan(fit = fit, algorithm = "HMC", control = list(metric = "unit_e", adapt_engaged = TRUE))

## 18: variational fullrank
vb(get_stanmodel(fit), algorithm = "fullrank")

## 19: variational meanfield
vb(get_stanmodel(fit), algorithm = "meanfield")
```

#### Side Effects:
Should be 0. This fixes the adaptation_info problem.

#### Documentation:
None.

#### Reviewer Suggestions: 
@bgoodri, @jgabry 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Bump.

How do I get travis working on this branch?

**Comment by bgoodri** [comment]
It looks like this branch doesn't have the changes due to cvodes moving to 2.9.0. I'll try to cherry-pick the relevant commits.

**Comment by syclik** [comment]
Thanks. For whatever reason it still builds locally.

**Comment by bgoodri** [comment]
What Stan Library branch is this supposed to be synced with?

**Comment by syclik** [comment]
feature/issue-1751-service-methods

**Comment by syclik** [comment]
If it's not working, let me know and I'll figure it out in the morning.

**Comment by syclik** [comment]
Bump. Time to review this. Make sure it works.

**Pull request merged**
