### PR TITLE
Support zero elements arrays

### PR DESCRIPTION
**Pull request by alyst**
Without these tiny fixes degenerated arrays cause errors in `rstan`.

### CODE REVIEW

**Comment by alyst** [comment]
I've rebased the PR to the `develop` head. Currently, empty 0-dim array is returned, if one of the dimensions is empty. I suppose it is more correct to return `length(d)`-dimensional empty array, because some downstream code might assume that the dimensions of the result always match the input.

Also I've replaced the indices generation with the one utilizing `rep()`. It should be much faster than the current one that sequentially increments the indices in the loop.

**Comment by bob-carpenter** [comment]
I'm not sure what the subtleties are for RStan, but the
dimensionality of arrays should definitely be preserved.

**Comment by jgabry** [comment]
Was this already dealt with in a separate commit or PR? If so we should close this. We have lots of outdated issues and PRs floating around.

**Comment by alyst** [comment]
@jgabry The code this PR patches is still there, so it should be relevant. I don't know why the devs hesitated to merge it. AFAIK there's no `rstan` test suite, so I don't know where to put the tests, but the patch was working for my projects.

**Comment by jgabry** [comment]
@alyst Ok thanks for following up. 

@maverickg looks like you mentioned this PR in a commit a while ago. Did you end up taking care of this issue?

**Comment by maverickg** [comment]
I guess it's irrelevant now, so I am closing it now. 

@alyst If you think it's important, please report it an issue first (with code to reproduce the problem).  In addition, we need code for unit tests and doc (if it's user facing) in a PR.

**Pull request closed without merging**
