### PR TITLE
Added accessor functions for HMC diagnostics

### PR DESCRIPTION
**Pull request by martinmodrak**
#### Summary:
Added functions to access diagnostics as mentioned in #494 

#### Intended Effect:
Programmatic access to HMC diagnostics

#### How to Verify:
Run the functions:
```
get_divergent_vector(object)
get_max_treedepth_vector(object)

get_n_divergent(object)
get_n_max_treedepth(object)

get_bfmi(object)
get_low_bfmi_chains(object)

```
where ```object``` is a stan fit.
#### Side Effects:
Hopefully none.

#### Documentation:
Done

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Institute of Microbiology of the Czech Academy of Sciences

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
1.  Can we drop the `_vector` suffix.  I don't think it's usual in R to indicate the return type.  

2.  I like `num_` better than `n_`, but if `n_` is an RStan or R convention, definitely follow the conventions.

3.  Is there a way to get the vector of the number of log density evals---it's the number of nodes in the binary tree that actually get evaluated.  The final doubling can short-circuit and return before completion, at which point it's pruned out and we don't know how many evals we did from just the final treedepth.  Also, it'd be nice to clarify in the doc if the treedepth includes the last doubling if it was rejected.

4.  The functions should check that the sampler used the right algorithm and return an appropriate message if they try to extract treedepth from a static HMC or other run.

**Comment by betanalpha** [comment]
n_leapfrog returns the number of gradient evaluations, including
subtrees that are rejected where as treedepth is the treedepth
only of tree that is kept.

**Comment by bob-carpenter** [comment]
Nice!

**Comment by martinmodrak** [comment]
So I added an accessor for ```n_leapfrog``` -> ```get_num_leapfrog_per_iteration```.

I am chaging the names to ```num_``` and did other name changes to have consistent naming ```get_divergent_vector``` -> ```get_divergent_iterations```. Just FYI ```num_``` seems to be used a bit more frequently in RStan interfaces (still, lots of variables in the code have ```n_```.

I added a check that it is a correct object.

The CI failures seem to be unrelated to my commits.

**Pull request merged**
