### PR TITLE
rstan.R/stanc.R: use message instead of cat for model translation & compilation

### PR DESCRIPTION
**Pull request by casallas**
- `message` can be silenced using `suppressMessages`
- This allows better integration with, e.g., `knitr` (see http://yihui.name/knitr/demo/output/)

### CODE REVIEW

**Comment by casallas** [comment]
it seems like those vignette errors that make the build fail were already present in the develop branch as of 7d6bf44c5b45b061e8e0f0b32f0a81050f37d4fb... the good news is that you can see the modified message lines in the Travis output:

```
TRANSLATING MODEL 'schools' FROM Stan CODE TO C++ CODE NOW.
COMPILING THE C++ CODE FOR MODEL 'schools' NOW.

TRANSLATING MODEL '8schools' FROM Stan CODE TO C++ CODE NOW.
COMPILING THE C++ CODE FOR MODEL '8schools' NOW.

TRANSLATING MODEL 'schools' FROM Stan CODE TO C++ CODE NOW.
COMPILING THE C++ CODE FOR MODEL 'schools' NOW.
```

**Comment by maverickg** [comment]
As function `message` would print it to standard error output, it is not used in the first place.

**Comment by casallas** [comment]
I see what you mean, and it indeed seems inconvenient that `message` directs its output to `stderr`. However, aside from using the seemingly cumbersome `sink`, I don't see any way to silence `cat` calls... 

It would seem like the best practice for this, is to use `message` (e.g., http://adv-r.had.co.nz/Exceptions-Debugging.html, http://yihui.name/knitr/demo/output/), unless there's a specific use case for which you currently need those messages printed in `stdout`?

**Comment by harrysouthworth** [comment]
I have exactly the same issue and was going to suggest exactly the same swapping from cat to message.

An alternative is to use the results="hide" option in the knitr chunk. I've just tried it and it works fine.

**Comment by jgabry** [comment]
Cleaning up old PRs that were never resolved. I think these statements are no longer printed so will close this.

**Pull request closed without merging**
