### PR TITLE
ggplot plotting functions

### PR DESCRIPTION
**Pull request by jgabry**
@bgoodri Here's a preliminary pull request for the ggplot functionality. I got rid of reshape2, so the only packages added to Description are ggplot2 and gridExtra. The easiest way to get a sense for the various plotting functions included is to build and then look at `?stan_plot` and `?stan_diag`.

### CODE REVIEW

**Comment by jgabry** [comment]
@bgoodri I've still got a few more things to push and I should edit the doc a bit more, but this is almost ready

**Comment by bgoodri** [comment]
OK. One thing is that you can't call `stan_demo()` in an example. Instead call `example(stan_read_csv)` to get a small `stanfit` object.

**Comment by bgoodri** [comment]
Also, when it is ready, you should have the `plot` method call `stan_plot` and the `traceplot` method call `stan_trace`, etc.

**Comment by jgabry** [comment]
Ok, will do

**Comment by jgabry** [comment]
@bgoodri, so you think we should remove the base graphics plots entirely
and replace them with the ggplots instead of offering both? (I'm fine with
that, although some users might still prefer the old ones).

Also, some of the plots don't really correspond to typical generics so most
of them would still need to be called by stan_*.

**Comment by bgoodri** [comment]
If the ggplot ones are better. Having separate functions that produce the
same plot conceptually is not ideal.

**Comment by bob-carpenter** [comment]
By all means, only support one.  Having to support multiple things
is just going to double all your work downstream.

I have a preference for that one being ggplot.
- Bob

**Comment by jgabry** [comment]
@bgoodri Ok, I think this should be working now. 

I changed the plot and traceplot methods, although I don't have a pairs plot yet so we can leave that one as is for now. Anything else you think this needs?

**Pull request merged**
