### PR TITLE
Feature/testify

### PR DESCRIPTION
**Pull request by bgoodri**
This PR adds the ability to export user-defined functions in a .stan program to the R global environment via Rcpp.

I also accidentally committed some changes to the DESCRIPTION files that were supposed to go into the develop branch, but whatever.

### CODE REVIEW

**Comment by bgoodri** [comment]
I tried to add a unit test

```
test_testify <- function() {
  require(rstan)
  model_code <- 
  '
    functions {
      matrix test(int i, real r, vector v, row_vector rv, matrix m);
      matrix test(int i, real r, vector v, row_vector rv, matrix m) {
        print("Working");
        return m;
      }      
    }
    parameters {real theta;}
    model {theta ~ normal(0,1);}
  '
  cat(model_code, file = 'testify.stan')  

  rstan:::testify(rstan:::stan_model('testify.stan'))
  m <- matrix(rnorm(9), 3, 3)
  out <- test(0L, 0.0, double(2), double(2), m)
  checkEquals(out, m)
}
```

but it failed to compile

```
ERROR in test_testify: Error in compileCode(f, code, language = language, verbose = verbose) :
  Compilation ERROR, function(s)/method(s) not created! Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> source -> file
```

How are these runit files supposed to work?

**Comment by maverickg** [comment]
For now, file [runRunitTests.R](https://github.com/stan-dev/rstan/blob/develop/rstan/tests/runRunitTests.R) run unit tests defined in folder [unitTests](https://github.com/stan-dev/rstan/tree/develop/rstan/tests/unitTests).  In fact, it is defined runRunitTests.R.

**Comment by maverickg** [comment]
how about supporting get the cpp code from `stanc` too?

**Comment by bgoodri** [comment]
I think this can be merged now since travis seems to be running out of RAM. I supported the output from stanc(). I haven't gotten the unit test to work, but I will put an example in the vignette to both show how to use it and to test that it works.

**Pull request merged**
