### PR TITLE
Feature/issue 197 remove writer

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

This updates `stan_fit.hpp` to work with the latest develop branch of Stan.
#### Intended Effect:

With stan-dev/stan#1601, some of the header files were removed. These were moved to RStan.
#### How to Verify:

This should compile and work exactly like the version without it.
#### Side Effects:

@bgoodri, can you double check the changes to `stan_fit.hpp`? It looks like the merge brought back in the section for advi... If you want that removed, just say so and I'll remove the sections.
#### Documentation:

None required.
#### Reviewer Suggestions:

@bgoodri

### CODE REVIEW

**Comment by syclik** [comment]
@bgoodri, just FYI, the failure was a travis-ci thing. It timed out trying to get R.

This is to get RStan up to develop. I'd wait on merging until after 2.8.0-1 or whatever you're working on for release now.

**Comment by ariddell** [comment]
Is there some way to track these refactoring tasks centrally? Should there be a meta-task in the `stan` repo? It also occurred to me that having a stan-3-stage-1 milestone or something like that would be useful.

**Comment by syclik** [comment]
There is a meta-task in the repo. This fix is post 2.8.0, but not Stan 3.
Once you release 2.8.0, I have a pull request ready to go.

(When releasing 2.8.0, if you use the v2.8.0 tagged version of the Stan
library, you won't need this patch.)

**Comment by ariddell** [comment]
PyStan 2.8.0.0 is out. Just waiting for the uploads of these monster OS
X wheels to make the announcement.

**Comment by bgoodri** [comment]
Okay to merge this? Anything else needed for 2.9?

**Comment by maverickg** [comment]
Some error messages cannot find their ways to the output; some units tests failed here: https://travis-ci.org/stan-dev/rstan/jobs/94535542

**Comment by maverickg** [comment]
I think I fixed the error message issue in the unit tests in develop branch.

**Comment by syclik** [comment]
Hi Jiqiang, does that one fix actually work? I tried the same thing and it
didn't pass. If so, then great! (and sorry for not getting it right the
first time.)

**Comment by maverickg** [comment]
@syclik It works.

**Pull request merged**
