### PR TITLE
Add save_progress option to sbc

### PR DESCRIPTION
**Pull request by jpritikin**
https://github.com/stan-dev/rstan/issues/641

This also makes it easy to pause a SBC run and resume it later.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Joshua N. Pritikin

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks! I haven’t run this yet but looks good at first glance. Will review soon.

**Comment by jpritikin** [comment]
Can idea when you can review this PR?

**Comment by bob-carpenter** [comment]
You will probably need @bgoodri or @jgabry to review it.  They might be waiting until it's fixed to the point of passing tests.

I don't know R well enough myself.

**Comment by jpritikin** [comment]
Needless to say, I believe these CI failures are unrelated to the proposed changes.

**Comment by jpritikin** [comment]
Okay, it's been 4 months. It's time to ask again for this PR to get merged. ;-)

**Review by bgoodri — APPROVED** [review]

**Pull request merged**
