### PR TITLE
StanHeaders 2.26 supports rstan 2.21

### PR DESCRIPTION
**Pull request by hsbadr**
`StanHeaders 2.26` supports `rstan 2.21` for reverse dependencies. This builds on https://github.com/stan-dev/rstan/pull/887 for backward compatibility, at least for the initial CRAN submissions. This targets `StanHeaders_2.26` branch while https://github.com/stan-dev/rstan/pull/887 targets the `develop` branch.

- [X] Update `stan-dev/stan` submodule.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@hsbadr are these now on 2.26.1?

**Comment by hsbadr** [comment]
> @hsbadr are these now on 2.26.1?

Not yet. We need to merge `release/v2.26.1` into `StanHeaders_2.26` branches. I'm waiting for @bgoodri, since he may have made local changes to https://github.com/stan-dev/math/tree/StanHeaders_2.26 and/or https://github.com/stan-dev/stan/tree/StanHeaders_2.26.

**But,** #887 is at `v2.26.1`.  The new packages are [here](https://github.com/stan-dev/rstan/actions/runs/579406194).

**Comment by rok-cesnovar** [comment]
Thanks. Just to double check. #887 is at develop or 2.26.1?

**Comment by hsbadr** [comment]
> Just to double check. #887 is at develop or 2.26.1?

Ah! Right. It's at `develop` after merging `v2.26.1` updates/patches.

@bgoodri Do you have any local patches to `StanHeaders_2.26` branches of `math`/`stan`? If not, I'll merge `release/v2.26.1`.

**Comment by hsbadr** [comment]
@rok-cesnovar This should be on `v2.26.1` now.

**Pull request merged**
