### PR TITLE
allow user to specify environment for exposed funs

### PR DESCRIPTION
**Pull request by davharris**
#### Summary:

In `expose_stan_functions`, allow the user to pass an environment object to `Rcpp::sourceCpp`
#### Intended Effect:

Allow for the addition of Stan-based functions to other environments and namespaces
#### How to Verify:

Given a suitable `stanmodel` object, the following code should save the functions to the `my_env` environment and then list the functions that were saved there.

```
my_env = new.env()
expose_stan_functions(stanmodel, env = my_env)
print(ls(my_env))
```
#### Side Effects:

None expected: the global environment will still be used by default.
#### Documentation:

Updated in the .Rd file for `expose_stan_functions`
#### Copyright and Licensing

copyright holder: David J. Harris

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks for the PR. I'll wait to merge until @bgoodri has a chance to take
a look, but it looks good to me and I can't think of any reason not to
allow specifying an environment. And the travis issues are unrelated so no
problem there. Out of
curiosity, what use case motivated this?

Jonah

**Comment by davharris** [comment]
@jgabry I was thinking about what it would take to use Stan under the hood in a package, and noticed that rstan was forcing everything into the global environment. It seemed like an easy problem to fix, so I went ahead and submitted a PR.

**Comment by jgabry** [comment]
Yeah makes sense. Pre-compiled exposed functions in packages is on its way.
Apparently it required a change that Ben made in the Stan C++ recently.

**Comment by davharris** [comment]
❤️

**Pull request merged**
