### PR TITLE
Enhance log

### PR DESCRIPTION
**Pull request by alyst**
This PR introduces 2 small enhancements to RStan logging:
1) `check_sfinstance_valid()` provides more diagnostic for Stan fit instance (simplifies debugging if e.g. stanfit/stanmodel objects are exported to parallel R sessions)
2) `verbose=FALSE` really works (completely disables diagnostic output) for sampling/optimizing

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks for submitting.  I'm going to have to leave
this to the RStan team to review, but I would suggest
renaming

  check_sfinstance_valid()

to something like

  validate_fit(fitobject);

You don't need both "check" and "valid" in the same
function name.

I also don't think we need it to be "validate_stan_fit"
because everything in the Stan interface is about Stan
by default.
- Bob

**Comment by bgoodri** [comment]
The best way to do the first part is to enhance the validity() method for a stanfit object in AllClass.R . For example, I have a local commit that changes it to

```
         validity = function(object) {
           if(length(object@sim) > 0) {
             NAs <- rapply(object@sim$samples, anyNA)
             if(any(NAs)) return(paste("The following variables have undefined values: ",
                                       unique(names(NAs[NAs])), collapse = ","))
           }
           return(TRUE) 
         }
```

There might be other things to check but I'm not sure under what conditions the things your patch checks for would trigger.

**Comment by jgabry** [comment]
Is this PR still relevant? It's been stale for a while and maybe some of the suggested behavior has been dealt with separately?

**Comment by jgabry** [comment]
> Is this PR still relevant? It's been stale for a while and maybe some of the suggested behavior has been dealt with separately?

I asked this in 2017 and got no response so will close.

**Pull request closed without merging**
