### PR TITLE
Fixes to SBC stuff

### PR DESCRIPTION
**Pull request by jpritikin**
#### Summary:
I email'd @jgabry about whether to submit some fixes to his SBC branch. He said, "yes."

#### Intended Effect:
Make work on some of my SBC models.

#### How to Verify:
Here is one example model, [prior for factor loading](https://discourse.mc-stan.org/t/what-is-a-suitable-prior-for-latent-factor-loadings/8803)

I have more if there is interest.

#### Code not submitted:
I put some work into improving the plot function. I'm not sure if I've got it right,
```
myplot <- function(x, thin = 4, perBin=4, ...) {
  thinner <- seq(from = 1, to = nrow(x$ranks[[1]]), by = thin)
  u <- t(sapply(x$ranks, FUN = function(r) colSums(r[thinner, , drop = FALSE])))
  numOfSamples <- ncol(u)
  parameter <- as.factor(rep(colnames(u), each = nrow(u)))
  d <- data.frame(u = c(u), parameter)
  numBins <- length(thinner)/perBin
  ymark <- qbinom(c(.005,1-.005), numOfSamples, numBins^-1)
  ggplot2::ggplot(d) + 
    ggplot2::geom_histogram(aes(x = u), bins=numBins, ...) + 
    xlim(0,length(thinner)) +
    ggplot2::facet_wrap('parameter') +
    geom_hline(yintercept=ymark[1], color='red') +
    geom_hline(yintercept=ymark[2], color='red')
}
```

Feel free to adopt or adapt this code as you see fit.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Joshua N. Pritikin

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
@jpritikin Thanks for this. I realized that the SBC PR https://github.com/stan-dev/rstan/pull/611 was already merged into `develop` and just saw that @bgoodri has already made some subsequent changes to the code on `develop`. After pulling those changes back into the `feature/SBC` branch it looks like there are now some conflicts with this PR now that I'm not sure how to resolve yet.

**Comment by jpritikin** [comment]
Oops! I didn't realize that I should be working on the develop branch. If you don't have time, I can try to merge things up when I get a chance.

**Comment by jgabry** [comment]
@jpritikin Thanks. I think I may have just successfully fixed the merge conflicts but can you take a peak at what I just pushed to make sure I didn't mess up anything you did?

**Comment by jpritikin** [comment]
Oops, I just merged the other way. I'll open a new pull

**Pull request closed without merging**
