### PR TITLE
Feature/andrewfy

### PR DESCRIPTION
**Pull request by bgoodri**
This does (part of) what 

http://mc-stan.org/rstan/stan.R

does in terms of reading (and optionally writing) a foo.rda file when passed a foo.stan file or a model_code.

Can you check f1822e820cbbdb5834e12c836f8e1f0a564b9bd4 to see if I got it right and then I'll do the parallel stuff.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Who are you asking to check that branch?  I think Andrew's
the customer you want to please here, but for that, you'll have
to wrap up a version of RStan he can install.
- Bob

**Comment by bgoodri** [comment]
I was mostly checking with @maverickg but anyone is welcome to test. I put the parallel stuff in too. I don't know exactly how it is going to open the progress file on Mac or Windows so any reports would be appreciated.

**Comment by maverickg** [comment]
I don't see any problem from the diff's in the PR.  So I will merge it.  We can fix it if we would find any problem.  One thing I don't know of is about writing the model to disk automatically: is it prone to load the DSO (DLL) multiple times and is it a problem?

**Comment by bgoodri** [comment]
I have not observed that to be an issue on Linux but maybe it is elsewhere?

> count <- 1
> while(TRUE) {
> - test <- readRDS("8schools.rda")
> - count <- count + 1
> - }
>   ^C
>   count
>   [1] 3263

Ben

**Comment by maverickg** [comment]
Well, it is not that simple. You don't use any of the functions in it. Anyway, it is just
I don't know and being unknown don't bother me.

**Comment by maverickg** [comment]
@bgoodri  have you checked opening the progress file in rstutio?  For the R Gui on Mac, it will open the file in an app called TextEdit, but TextEdit does not give any option to reload(refresh) the text file.

**Comment by bgoodri** [comment]
Right, I saw this issue come up a long time ago

http://stackoverflow.com/questions/24832030/exceeded-maximum-number-of-dlls-in-r

Part of the reason I hope it is not a problem is that if people are running
the chains in parallel, the thing gets loaded in a separate R process,
which is closed when it is finished.

**Comment by bgoodri** [comment]
I was worried about that. For me, it opens by default in Kate. I wasn't
able to get it to do anything useful in RStudio because file.show and
rstudio::viewer and whatnot do not actually show progress. Try setting

options(browser = 'safari')

or something.

**Comment by maverickg** [comment]
By default, in Mac

```
> getOption("browser")
[1] "/usr/bin/open"
```

This `open` is like `gvfs-open` in Linux. 

If you really want to set it to Safari, the following would work. 

```
options(browser='/Applications/Safari.app/Contents/MacOS/Safari')
```

But it seems to be more complicated.

**Comment by bgoodri** [comment]
Do you know what happens on Windows? I could hard-code to Safari on a Mac I
guess.

**Comment by maverickg** [comment]
On windows, by default, it would not open the file since 

```
> isatty(stdout())
[1] TRUE
```

If I set `show_progress` to be `TRUE`, the text file would be opened by the default program to open a text file (typically the Notepad, which does not allow you to refresh/reload either).  And on windows, you cannot use option `browser` since it is `NULL`. 

By the way, if you hardcode it on Mac, just realized you can use (see the man page of open [here](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/open.1.html))

```
open -a Safari progress.txt 
```

**Comment by bgoodri** [comment]
Okay, I think if the progress shows up in the Windows GUI, that is fine.
For RStudio on Windows, I guess isatty(stdout()) is FALSE so we'll have to
come up with something there.

**Comment by maverickg** [comment]
I did not try RStudio on windows.  What I said is on R-Gui on Windows.  
And I was saying the file is not opened by default because isatty(stdout()) is TRUE.  It needs to be FALSE so that open_progress might be TRUE.

**Comment by bgoodri** [comment]
I got you. The main thing is to
- Avoid not showing any progress
- Avoid showing all the "progress" only when sampling() is finished

Can you try develop again on Mac / Windows? I tried harder to force it into
a web browser.

**Comment by bob-carpenter** [comment]
I think it's a bad idea to pop open a third-party application
by default.  Can that be off by default and only turned on
by the user if requested?  I just hate hate hate having to
always be closing the useless crap editor textedit.
- Bob

**Comment by bob-carpenter** [comment]
Right now, the progress is all delayed on the Mac GUI,
but shows up from the terminal.  They clearly did something
bad to buffering with the GUI.  No idea what RStudio does.

Is it just impossible to get progress shown in the actual
app that called it?  I know Andrew wants something minimal,
but my preferences differ and I'm willing to go with Andrew's
as the default if it's OK with Ben and Jiqiang.  The key was
that he didn't want 10 lines of output per chain (though seemed
to be OK with all the boilerplate around print, which I think
should be trimmed).

I don't use RStudio for anything but knitr because of its 
tendency to crash, at least on MacOS.  Speaking of which, I was 
talking to an RStan user here who also experienced crashes in RStudio but
not in the GUI or terminal, so he said he got things put together in
RStudio, but then did all his turns from the R terminal.  I believe
Avi from Harvard had the same experience --- developed in RStudio,
then ran in R terminal because it didn't crash.

So maybe we're doing something wrong in interfacing with RStudio?
- Bob

**Comment by bgoodri** [comment]
It is off by default because it only uses one thread by default, in which
case print_progress goes to the main R(Studio) process. But it is on by
default if someone chooses to use multiple cores. I don't think there is a
great solution to print progress to the main R(Studio) process when the
thing is actually in a background process. There is the RcppProgress
package, which I looked at but haven't tried. The best thing I could come
up with is have the background processes write to a file that is opened by
an external application (hopefully Safari now on a Mac).

**Comment by bgoodri** [comment]
By right now, you mean rstan < 2.6.2, right? That is the behavior I'm try
to avoid here. Or do you mean it still persists for you if you build rstan
from GitHub?

**Comment by bob-carpenter** [comment]
> On Mar 17, 2015, at 10:33 AM, bgoodri notifications@github.com wrote:
> 
> It is off by default because it only uses one thread by default, in which
> case print_progress goes to the main R(Studio) process. But it is on by
> default if someone chooses to use multiple cores. I don't think there is a
> great solution to print progress to the main R(Studio) process when the
> thing is actually in a background process. There is the RcppProgress
> package, which I looked at but haven't tried. The best thing I could come
> up with is have the background processes write to a file that is opened by
> an external application (hopefully Safari now on a Mac).

I understand that.  Is the problem just that we can't do anything
in the main R process that kicked things off until everything's done?
If so, I don't see a good solution.

I'd much rather a browser than a text editor!  Or just a terminal
running running tail -f:

http://en.wikipedia.org/wiki/Tail_(Unix)#File_monitoring

Of course, that requires the terminal, which we can't guarantee
a Windows user will have unless they have cygwin installed.
- Bob

**Comment by bob-carpenter** [comment]
Yes, I mean for 2.6.0.  I haven't tried the new
version because I don't know how to build it and have
been working on other things.
- Bob

**Comment by maverickg** [comment]
> I got you. The main thing is to
> - Avoid not showing any progress

No, you have not.  I try again. Now the default value of `open_progress` is 

```
 open_progress = interactive() && !isatty(stdout())
```

So it would be FALSE since you have the following on Windows. 

```
> isatty(stdout())
[1] TRUE
```

For now, Mac is using Safari to open the file. 

For windows, set brower to 'start' does not work. It does not open any file.

**Comment by maverickg** [comment]
I thought about changing the suffix of the text file to html, so that it would be opened by a web browser.  But on Windows, the web browser does not render a line break without `<br>`.

**Comment by maverickg** [comment]
Ok, how about create another html file that would include the text file?  I suppose you cannot even load the text file automatically with some javascript.

**Comment by bgoodri** [comment]
I think I have got it working now. I had assumed that because
isatty(stdout()) is TRUE under the Windows GUI that it would print the
progress to the screen, which would have been fine except that it is not
the case. So, now I just have it hard-coded to call Internet Explorer on
Windows like it does for Safari on Mac.

**Comment by bob-carpenter** [comment]
Firing up IE seems nasty.  It looks like "start" may fire up 
the default browser:

https://social.msdn.microsoft.com/Forums/ie/en-US/5bf91e62-7be9-4f1d-9bac-5b2a4dd8ced7/starting-the-default-browser-from-commandline?forum=iewebdevelopment

HTML _should_ only have a newline if there's a <br /> --- it's
not supposed to be whitespace sensitive other than in a <pre> ... </pre>
context.  One alternative would be to wrap output in a <pre> ... </pre>
I don't know what happens when you've only seen the start <pre> and no
end, but web browsers tend to be pretty robust.
- Bob

**Comment by bgoodri** [comment]
That is what I tried first. However,

options(browser = "start")
browseURL("www.google.com")

fails on Windows due to the way that start gets quoted I think. At least we
know Internet Explorer is present on a Windows system. I don't think it is
any more nasty than starting Safari on a Mac. And less nasty than not
having any progress indication.

**Comment by bob-carpenter** [comment]
Agreed.  Firing up Safari by default on Mac is also nasty!

I assume there's no way to get the behavior of "tail -f"
through R itself by polling the file you create?  Could
you spin up yet another process to do it?  
- Bob

**Comment by bgoodri** [comment]
That is doable on any computer with the tail program installed, which
excludes Windows. How would you check for it on a Mac?

**Comment by bob-carpenter** [comment]
tail comes pre-installed as part of Mac OSX.  I suppose someone
might get rid of it somehow, so I don't know if it's guaranteed
to be installed (of course the same goes for Safari --- my ignorance
of whether it can be trashed, that is).
- Bob

**Comment by bgoodri** [comment]
There does not seem to be an programatic way to get tail -f to stop polling
the file when Stan is finished. Even if I remove the file it is polling,
the tail process does not die.

**Pull request merged**
