### PR TITLE
Feature/move stan_demo

### PR DESCRIPTION
**Pull request by bgoodri**
CRAN wants us to not have a separate rstanDemo package, so I had to move stan_demo.R and stan_demo.Rd back to the rstan package. But in addition, CRAN doesn't want all the bulk that comes with the example-models sub-repo, so now stan_demo() should ask if you want to download that from GitHub to either the include directory where rstan is installed (which may not be writable) or to a temporary directory. It works for me on Linux, but can you check on a Mac and / or Windows before you merge it.

### CODE REVIEW

**Comment by maverickg** [comment]
Okay, I will test it and then merge.

**Comment by maverickg** [comment]
seems to be fine on mac.

**Comment by maverickg** [comment]
by the way, is RCurl enough for downloading file using https?

**Comment by bgoodri** [comment]
I am not sure. I tried RCurl briefly and could not get it to handle
github's redirects, although I could do it from a shell. The httr stuff
worked on the first try. I guess that part of the code will not be called
that often.

**Comment by maverickg** [comment]
You are right that part would not be called much.  I was just surprised that httr requires quite a few of packages.  

Anyway, adding option `.opts=curlOptions(followlocation=TRUE))` to RCurl's method is needed for using RCurl.  So I will switch to RCurl.

**Pull request merged**
