### PR TITLE
Fix effective sample size

### PR DESCRIPTION
**Pull request by avehtari**
#### Summary:

Fixes effective sample size computation #484

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Aki Vehtari

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by avehtari** [comment]
@bgoodri  code is currently working, but I haven't been able to figure out how to compare to n_eff code in stan repo, and I couldn't figure out how to run rstan tests for effective sample size computation.

**Comment by avehtari** [comment]
I now found runit.test.chains.R, but even the old results do not make sense compared to tests in CmdStan

**Comment by avehtari** [comment]
Ah, `rstan/rstan/inst/unitTests/testdata/blocker1.csv` has different values compared to `stan/src/test/unit/mcmc/test_csv_files/blocker.1.csv' same for '...2.csv'
When I compute N_eff's using csv's in stan repo, I get same N_eff's at least with 6 digit accuracy.

**Comment by avehtari** [comment]
Code is correct and tests have been updated. @bgoodri how do I run tests?

**Comment by bgoodri** [comment]
They run automatically

**Comment by avehtari** [comment]
I mean how do I run them in my computer? I didn't get any errors before, so I guess no tests were run automatically in my computer.

**Comment by bgoodri** [comment]
If you go into the first rstan subdirectory, you can do

make test-R

but you may have to install the up-to-date version first

**Comment by avehtari** [comment]
jenkins says
```
> install.packages("devtools")
Warning in install.packages("devtools") :
  'lib = "/Library/Frameworks/R.framework/Versions/3.2/Resources/library"' is not writable
Error in install.packages("devtools") : unable to install packages
Execution halted
script returned exit code 1
```
which seems something I can't fix?

**Comment by bgoodri** [comment]
That only happens on the Mac.

**Comment by avehtari** [comment]
So is there something I should do before this can be merged?

**Comment by bgoodri** [comment]
@seantalts How do you ask the tests to be run on Linux instead of the Mac?

**Comment by seantalts** [comment]
If you want to run this all on Linux, you can change this line: https://github.com/stan-dev/rstan/blob/develop/Jenkinsfile#L2
To
```
agent { label 'linux' }
```

**Comment by bgoodri** [comment]
In general, it would be good to test rstan on a Mac because Macs do all
kinds of weird things. But that doesn't work because of permissions.

For this particular pull request, it is just changing the C++ to match what
upstream does, so I would expect that if it works on Linux it works
platform-wide.

**Comment by seantalts** [comment]
Can't you change the lib directory for R to a local one so you can install packages?

**Comment by bgoodri** [comment]
If I had access to that machine, probably.

**Review by bgoodri — APPROVED** [review]
I am going to assume this is correct even though we cannot get the testing framework to cooperate. If there are problems, we can correct them on the master branch.

**Pull request merged**
