### PR TITLE
Backport stanc3 bugfix for ternary ops with expressions

### PR DESCRIPTION
**Pull request by andrjohns**
@hsbadr 

This PR updates the `stanc.js` file to backport the bugfix from https://github.com/stan-dev/stanc3/pull/977 for handling ternary operations with Eigen expressions. This will be needed for the `multinma` package.

I used the same [stanc3 branch](https://github.com/stan-dev/stanc3/tree/lexer-patch-v2.26.1) previously used for backporting stanc3 patches in #988

### CODE REVIEW

**Comment by hsbadr** [comment]
@andrjohns I'll need a release out of this to ship the JS in RStan.

**Comment by hsbadr** [comment]
You may test it with the latest version of RStan v2.26.

**Comment by andrjohns** [comment]
No rush on shipping a new version just yet, I'm still working through other revdep failures for rstan 2.26 so there might be other patches still to come

**Review by hsbadr — APPROVED** [review]
LGTM. Since 2.26 is a temp release, I'll merge this into 2.26.15.

**Pull request merged**
