### PR TITLE
For 2.18

### PR DESCRIPTION
**Pull request by bgoodri**
#### Summary:

Prepare for 2.18 release

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
@seantalts I don't know what test machine still has R 3.2.x on it but R 3.4.0 is required for anything involving **rstan** 2.18.0 or later.

**Comment by seantalts** [comment]
Looks like the mac pro. I'll see if I can upgrade it.

**Comment by seantalts** [comment]
It's upgraded

**Comment by syclik** [comment]
@bgoodri, can you change the behavior so NaN is allowed output from Stan?
The parameters will never be NaN, but it's possible for generated
quantities to have it (think 0 / 0 via underflow).

**Comment by bgoodri** [comment]
I can, but things are going to break later that assume no NaNs. Even the
summary.

**Comment by syclik** [comment]
Ok. The broken things should probably be fixed soon? This has been valid in
the language since generated quantities have had been introduced.

parameters {
  real theta;
}
model {
  theta ~ normal(0, 1);
}
generated quantities {
  real nan;
  nan = 0.0 / 0.0;
}

It's nonsensical, but valid.

**Comment by bgoodri** [comment]
I guess if we are not going to throw an error in that case, then we have to
make everything NaN-aware.

**Comment by riddell-stan** [comment]
I gather this needs to be in PyStan too. Is there a test verifying correct behavior somewhere in RStan / CmdStan?

**Comment by bgoodri** [comment]
Not that I know of. It doesn't really work in RStan anyway.

**Pull request merged**
