### PR TITLE
Introduce functions to check hmc diagnostics

### PR DESCRIPTION
**Pull request by jgabry**
#### Summary:

Introduces several functions to print summaries of important HMC diagnostics. These are adapted from code @betanalpha has in his `stan_utility` file.

* `check_hmc_diagnostics` prints an overall summary by calling each of the following functions internally (they can also be called individually since they're all exposed):

* `check_divergences` prints the number (and percentage) of iterations that ended with a divergence 
* `check_treedepth` prints the number (and percentage) of iterations that saturated the max treedepth
* `check_energy` prints E-BFMI values for each chain for which E-BFMI is less than 0.2

#### How to Verify:

```r
# fit model that has some problems
schools <- stan_demo("eight_schools", control = list(max_treedepth = 5)) 
check_hmc_diagnostics(schools)
```

The printed output should look something like this (except in color):

```
Divergences:
145 of 4000 iterations ended with a divergence (3.625%).
Try increasing 'adapt_delta' to remove the divergences.

Tree depth:
277 of 4000 iterations saturated the maximum tree depth of 5 (6.925%).
Try increasing 'max_treedepth' to avoid saturation.

Energy:
E-BFMI indicated possible pathological behavior:
  Chain 1: E-BFMI = 0.171
E-BFMI below 0.2 indicates you may need to reparameterize your model.
```

You can also run the individual check functions: 

```r
check_divergences(schools)
check_treedepth(schools)
check_energy(schools)
```

#### Documentation:

Added doc in `check_hmc_diagnostics.Rd`.

#### Reviewer Suggestions: 

@betanalpha How do these look?

@bgoodri If they look OK to @betanalpha, can we get these in the next release so we have them for courses?

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bgoodri** [comment]
It should also give a link to the webpage on warnings.

**Review by betanalpha — CHANGES_REQUESTED** [review]
This looks good, although you ended up grabbing an older version of `check_energy` which doesn't have the default output.  

```
check_energy <- function(fit) {
  sampler_params <- get_sampler_params(fit, inc_warmup=FALSE)
  no_warning <- TRUE
  for (n in 1:length(sampler_params)) {
    energies = sampler_params[n][[1]][,'energy__']
    numer = sum(diff(energies)**2) / length(energies)
    denom = var(energies)
    if (numer / denom < 0.2) {
      print(sprintf('Chain %s: E-BFMI = %s', n, numer / denom))
      no_warning <- FALSE
    }
  }
  if (no_warning)
    print('E-BFMI indicated no pathological behavior')
  else
    print('E-BFMI below 0.2 indicates you may need to reparameterize your model')
}
```

I am hesitant to add links every time this is called as Ben recommended as it ends up dumping way too much to the screen  -- maybe a verbose version where the links to the warning webpage are printed if warnings are flagged?  Or at the very least throw the webpage up on the function docs.

**Comment by jgabry** [comment]
Ok I added the url in the documentation (rather than printing it out every time). 

@betanalpha when you say `check_energy` is missing the default output, do you mean the output when there are no problems detected? The `check_energy` function in the PR is 

```r
check_energy <- function(object) {
  energies_by_chain <- sampler_param_matrix(object, "energy__")
  EBFMIs <- apply(energies_by_chain, 2, function(x) {
    numer <- sum(diff(x) ^ 2) / length(x)
    denom <- var(x)
    numer / denom
  })
  bad_chains <- which(EBFMIs < 0.2)

  if (!length(bad_chains)) {
    message("E-BFMI indicated no pathological behavior.")
  } else {
    message(
      "E-BFMI indicated possible pathological behavior:\n", 
      sprintf("  Chain %s: E-BFMI = %.3f\n", bad_chains, EBFMIs[bad_chains]),
      "E-BFMI below 0.2 indicates you may need to reparameterize your model."
    )
  }
}
```
so even if there are no issues prints a message saying "E-BFMI indicated no pathological behavior."
For a model with no diagnostic issues at all the output of `check_hmc_diagnostics` looks like this: 

```
Divergences:
0 of 500 iterations ended with a divergence.

Tree depth:
0 of 500 iterations saturated the maximum tree depth of 15.

Energy:
E-BFMI indicated no pathological behavior.
```

So I think it's all there. Or did I misunderstand what you were saying?

**Comment by betanalpha** [comment]
Yeah, my bad.  It's the correct version.

**Review by betanalpha — APPROVED** [review]

**Pull request merged**
