### PR TITLE
remove withr and make -march=native in makevars a warning on windows

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Summary:

I think the `withr` stuff I added had good intent but it looks like users are getting windows specific errors because of something that happened in withr. The intent of those functions was just to remove `-march=native` on windows, but if the solution also causes answers, seems bad. 

https://discourse.mc-stan.org/t/new-error-cleanup-makevar-old-argument-rmu-is-missing-with-no-default/18137/19

So instead all this does is look at the users makevars and if it see's `-march=native` in the CXXFLAGS on windows it gives a warning. I think this is less invasive which is nice and it has an option to disable the warning if the user is not using rtools or whatever reason they want to get rid of the warning

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
Can someone review this?

**Comment by jgabry** [comment]
Is most of the diff here just whitespace? When I go to the "Files changed" tab it's hard to tell what code actually got changed.

**Comment by SteveBronder** [comment]
Oh woof, yeah sorry my IDE removes whitespace at the end of the lines when I save in a file.

The changes are

1. In [`cxxfunctionplus`](https://github.com/stan-dev/rstan/pull/857/files#diff-3efed50c5987ef75d3a7d7926de190c7R160) and [`expose_stan_functions`](https://github.com/stan-dev/rstan/pull/857/files#diff-5e4e8e3f1133656358e0da9b66d755a4R84) instead of doing the makevar cleaning stuff for windows we just have a new function `.warn_march_makevars()` that will warn windows users that they should not have `-march=native` as a compiler flag

2. Instead of importing all of `withr` we just grab the [`makevar_user`](https://github.com/stan-dev/rstan/pull/857/files#diff-c8af6d5a55d29ad6cf5bcf2573a43bb1R207) function and put it in `makefile_op.R`. I think that's better than importing all of withr.

3. Instead of `.remove_march_makevars()` we have a new function `.warn_march_makevars()` which just scan's the users makevars (if they have one) and if they have `-march=native` anywhere we warn them to remove it.

4. This also includes a new `rstan_option` called [`disable_march_warning`](https://github.com/stan-dev/rstan/pull/857/files#diff-d149e60f23d6d9bc8b5c4f3d88e80ef2R84) so if users really know what they are doing they can just set that to suppress the error message

The rest of it is just whitespace

**Comment by andrjohns** [comment]
Will this trip in cases where there are multiple ```CXXFLAGS``` listed? For example, my ```Makevars.win``` has:
```
CXX14FLAGS += -O3 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2
CXX14FLAGS += -Wno-ignored-attributes -Wno-unused-function -Wno-parentheses
CXX14FLAGS += -Wno-deprecated-declaration
```

Will the warning go off regardless of which line the ```-march=native``` is in?

**Comment by bgoodri** [comment]
I think we should `Sys.setenv(R_MAKEVARS_USER = "NUL")` on Windows if `-march=native` is found and throw a message saying that if they want to customize their `CXX14FLAGS` they have to get rid of the `-march=native` part. It is probably too hard to figure out whether a `-march=native` has been superseded by a subsequent statement.

**Comment by SteveBronder** [comment]
> Will the warning go off regardless of which line the -march=native is in?

Yeah it will go off on any of them

> I think we should Sys.setenv(R_MAKEVARS_USER = "NUL") on Windows if -march=native is found and throw a message saying that if they want to customize their CXX14FLAGS they have to get rid of the -march=native part. It is probably too hard to figure out whether a -march=native has been superseded by a subsequent statement.

So something like:

```R
  if (WINDOWS) {
    has_march = .warn_march_makevars()
    if (has_march) {
      user_makevar = Sys.getenv("R_MAKEVARS_USER")
      Sys.setenv(R_MAKEVARS_USER = NULL)
      on.exit({
        Sys.setenv(R_MAKEVARS_USER = user_makevar)
      })
    }
  }
```

Where we change the warning to mention that we are going to ignore their Makevars. I'm fine with that, though I kind of like just having the warning because there's probably some user out there that is not using mingw and if so they may be able to use `-march=native` for their setup (or if this bug in mingw gets fixed in the future)

**Comment by bgoodri** [comment]
Rcpp is not known to work on Windows outside of RTools so I am not too
worried about it.

**Comment by SteveBronder** [comment]
Cool cool I just updated it with the above to set/unset makevars when we see `-march=native`

**Comment by SteveBronder** [comment]
Are there times on.exit() would not be called? If so the change I made for the above to swap in and out the makevars if we see `-mtune=native` could cause an error like below

https://discourse.mc-stan.org/t/new-error-cleanup-makevar-old-argument-rmu-is-missing-with-no-default/18137/37?u=stevebronder

**Comment by bgoodri** [comment]
on.exit() is always called

**Comment by SteveBronder** [comment]
Cool cool then I think this should be good to go!

**Comment by SteveBronder** [comment]
Also if you want to ignore the whitespace changes on github when you go to "Files Changed" you can click the little widget next to "Jump To" and click the "Hide whitespace changes" mark to hide all those when looking at the code changes

**Comment by jgabry** [comment]
With https://github.com/stan-dev/rstan/issues/866 and other similar issues reported here and discourse it would be good to get this merged. @bgoodri Is this ready from your perspective?

**Pull request merged**
