### PR TITLE
Feature/csr extract

### PR DESCRIPTION
**Pull request by bgoodri**
not working yet

### CODE REVIEW

**Comment by bgoodri** [comment]
@bob-carpenter @syclik @sakrejda 
I am getting this weird compiler error on the rstan `feature/csr_extract` branch. Do you know what it means? The first lines of sparse_extractors.cpp are just

```
RcppExport SEXP extract_sparse_components(SEXP A) {
  Eigen::SparseMatrix<double> AA(Rcpp::as<Eigen::SparseMatrix<double> >(A));
  Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA);
```

and similarly for `csr_extract_v` and `csr_extract_u`:

```
sparse_extractors.cpp:11:75: error: no matching function for call to ‘csr_extract_w(Eigen::SparseMatrix<double, 0, int>&)’
   Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA);
                                                                           ^
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math.hpp:209:0,
                 from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:4,
                 from sparse_extractors.cpp:2:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_w.hpp:24:5: note: candidate: template<class T> const Eigen::Matrix<Scalar, -1, 1> stan::math::csr_extract_w(const Eigen::SparseMatrix<_Scalar, 1>&)
     csr_extract_w(const Eigen::SparseMatrix<T,  Eigen::RowMajor>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_w.hpp:24:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:11:75: note:   template argument ‘0’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
   Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA);
                                                                           ^
sparse_extractors.cpp:11:75: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::SparseMatrix<_Scalar, 1>’
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math.hpp:209:0,
                 from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:4,
                 from sparse_extractors.cpp:2:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_w.hpp:41:5: note: candidate: template<class T, int R, int C> const Eigen::Matrix<Scalar, -1, 1> stan::math::csr_extract_w(const Eigen::Matrix<T, R, C>&)
     csr_extract_w(const Eigen::Matrix<T,  R, C>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_w.hpp:41:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:11:75: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::Matrix<T, R, C>’
   Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA);
                                                                           ^
sparse_extractors.cpp:15:52: error: no matching function for call to ‘csr_extract_v(Eigen::SparseMatrix<double, 0, int>&)’
   std::vector<int> v = stan::math::csr_extract_v(AA);
                                                    ^
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math.hpp:210:0,
                 from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:4,
                 from sparse_extractors.cpp:2:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_v.hpp:27:5: note: candidate: template<class T> const std::vector<int> stan::math::csr_extract_v(const Eigen::SparseMatrix<_Scalar, 1>&)
     csr_extract_v(const Eigen::SparseMatrix<T, Eigen::RowMajor>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_v.hpp:27:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:15:52: note:   template argument ‘0’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
   std::vector<int> v = stan::math::csr_extract_v(AA);
                                                    ^
sparse_extractors.cpp:15:52: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::SparseMatrix<_Scalar, 1>’
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math.hpp:210:0,
                 from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:4,
                 from sparse_extractors.cpp:2:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_v.hpp:45:5: note: candidate: template<class T, int R, int C> const std::vector<int> stan::math::csr_extract_v(const Eigen::Matrix<T, R, C>&)
     csr_extract_v(const Eigen::Matrix<T,  R, C>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_v.hpp:45:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:15:52: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::Matrix<T, R, C>’
   std::vector<int> v = stan::math::csr_extract_v(AA);
                                                    ^
sparse_extractors.cpp:16:52: error: no matching function for call to ‘csr_extract_u(Eigen::SparseMatrix<double, 0, int>&)’
   std::vector<int> u = stan::math::csr_extract_u(AA);
                                                    ^
In file included from sparse_extractors.cpp:2:0:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:26:5: note: candidate: template<class T> const std::vector<int> stan::math::csr_extract_u(const Eigen::SparseMatrix<_Scalar, 1>&)
     csr_extract_u(const Eigen::SparseMatrix<T,  Eigen::RowMajor>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:26:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:16:52: note:   template argument ‘0’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
   std::vector<int> u = stan::math::csr_extract_u(AA);
                                                    ^
sparse_extractors.cpp:16:52: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::SparseMatrix<_Scalar, 1>’
In file included from sparse_extractors.cpp:2:0:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:42:5: note: candidate: template<class T, int R, int C> const std::vector<int> stan::math::csr_extract_u(const Eigen::Matrix<T, R, C>&)
     csr_extract_u(const Eigen::Matrix<T,  R, C>& A) {
     ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:42:5: note:   template argument deduction/substitution failed:
sparse_extractors.cpp:16:52: note:   ‘Eigen::SparseMatrix<double, 0, int>’ is not derived from ‘const Eigen::Matrix<T, R, C>’
   std::vector<int> u = stan::math::csr_extract_u(AA);
                                                    ^
/usr/lib/R/etc/Makeconf:143: recipe for target 'sparse_extractors.o' failed

```

**Comment by sakrejda** [comment]
I think it means AA needs to be row-major and its column major by default.
It's just missing a constructor argument. I'll take a peak at the branch
this morning. K

**Comment by sakrejda** [comment]
Where do I find the StanHeaders 2.7.1 to test this with? It doesn't seem to
be a github repo.  I just modified the DESCRIPTION to accept 2.7.0 but I
assume that will cause problems.

Krzysztof


Krzysztof Sakrejda

Department of Biostatistics and Epidemiology
University of Massachusetts, Amherst
319 Morrill Science Center South
611 N. Pleasant Street
Amherst, MA 01003

work #: 413-325-6555
email: sakrejda@umass.edu

2015-09-10 1:39 GMT-04:00 bgoodri <notifications@github.com>:

**Comment by bgoodri** [comment]
If you are in the top-level rstan directory for the GitHub clone, you can
just do

git pull
git checkout feature/csr_extract
R CMD build StanHeaders
R CMD INSTALL StanHeaders_2.8.0.tar.gz

Then if you try to do

R CMD build rstan/rstan

you will see the compiler error.

**Comment by sakrejda** [comment]
My previous comment was partly wrong.  The problem is that we no longer have CSC-format extractors (we chose only CSR) but the solution is a little messy. I tried to do a branch but I can't get the right StanHeaders/rstan/Math combo so that "R CMD build" works so I'm just documenting the solution here.  In R, doing this: 

```
A <- matrix(rnorm(100), 10, 10)
 AA <- Matrix(A,sparse=TRUE)
```

Makes AA into a compressed sparse column (CSC) matrix.  We only have CSR format extractors in Stan because that's faster for matrix-by-vector multiplication (and particularly for gradients using dot-product).  

I had an R helper function (below) because doing a transpose before extracting components exchanges row and column definitions. So R can pass in a CSC matrix, and if we want the CSR representation we just transpose it (which is as good as R's sparse matrix transpose function) and then use the regular CSC extractors.  

```
extract_sparse_parts <- function(A, type='CSC') {
  if (class(A) == 'matrix') {
    A <- Matrix(A, sparse=TRUE)
  }
  if (type == 'CSR') {
    A <- t(A)
  }
  if (class(A) == 'dgCMatrix') {
    o <- .Call("extract_sparse_components",A)
  } else {
    stop("Argument 'x' must either be of class 'matrix' or 'dgCMatrix'.")
  }
  o[['type']] <- type
  return(o)
}
```

So the solution is to change:

```
  Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA);
```

into 

```
  Eigen::Matrix<double, Eigen::Dynamic,1> w = stan::math::csr_extract_w(AA.transpose());
```

because we do have a CSR-format signatue. This will be as good as Eigen's sparse matrix transpose.  In rstan the implication is that the helper function needs to change.  It only needs to transpose if we want to extract CSC-format components.  New helper definition is like this: 

```
extract_sparse_parts <- function(A, type='CSR') {
  if (class(A) == 'matrix') {
    A <- Matrix(A, sparse=TRUE)
  }
  if (type == 'CSC') {
    A <- t(A)
  }
  if (class(A) == 'dgCMatrix') {
    o <- .Call("extract_sparse_components",A)
  } else {
    stop("Argument 'x' must either be of class 'matrix' or 'dgCMatrix'.")
  }
  o[['type']] <- type
  return(o)
}
```

I can do a pull request once I figure out how to get R CMD build going...

**Comment by bgoodri** [comment]
OK, I can probably figure it out after my class. Thanks!

**Comment by sakrejda** [comment]
@bgoodri Hope it's not too confusing but I followed your instructions to get R CMD build going and the version I pushed passes those checks.  I didn't know how you were going to do the interface stuff so I'm leaving the R-land helper functions to you.  Just remember now if you pass in an R CSC format matrix (default from R's Matrix package), the function in sparse_extractors.cpp will return the CSR-format representation due to the transpose it does to match R's matrix to the signatures in Stan.  Probably worth having a unit test to make sure this goes through right.

**Comment by sakrejda** [comment]
This is failing on some update, the extractor C++ code builds fine.

**Comment by bgoodri** [comment]
Should the R function be defaulting to type = "CSR" or would "CSC" be better? It seems like most (all?) of the time, the input matrix would be in CSC format and the user wants the `w`, `u`, and `v` that is compatible with `csr_matrix_times_vector`.

**Comment by sakrejda** [comment]
Documentation would've helped, sorry.  A couple of points, not sure how
much of this is obvious so I'll just do it all.  The whole thing hinges on
how the difference between CSC and CSR formats is whether things are done
by row or column and the fact that a transpose interchanges the meaning of
row/column indices in a matrix.

a) The "type" argument gives the desired output format, regardless of the
input format.
b) R's sparse matrices (from the Matrix package) are in CSC format (no
alternative), and by default we want CSR-format w/v/u to be compatible with
csr_matrix_times_vector
c) We only have a w/v/u extractor (C++ Stan API) that accepts a CSR format
matrix.
d) Transposing a matrix interchanges column and row definitions, so

X^(CSC) is a matrix in (internally) CSC format
X^(CSR) is a matrix in (internally) CSR format
g maps X^(CSR) -> {w,v,u}, written as g(X^(CSR))
g(X^(CSC)) doesn't exist
g(t(X^(CSC)) = g(X^(CSR))
- That's why the rstan C++ function I suggested does a transpose before
  calling the extractor (since there is only a CSR extractor)
- That's why the rstan R-level function I suggested does an extra transpose.

extract_sparse_parts <- function(A, type='CSR') {
  if (class(A) == 'matrix') {
    A <- Matrix(A, sparse=TRUE)  ## If it's not a sparse matrix make it
into one
  }
  if (type == 'CSC') {
    A <- t(A)  ## If we want CSC output (not default, not useful for rstan,
just for completeness) do an extra transpose.
  }
  if (class(A) == 'dgCMatrix') {
    o <- .Call("extract_sparse_components",A)
  } else {
    stop("Argument 'x' must either be of class 'matrix' or 'dgCMatrix'.")
  }
  o[['type']] <- type
  return(o)
}

Krzysztof Sakrejda

Department of Biostatistics and Epidemiology
University of Massachusetts, Amherst
319 Morrill Science Center South
611 N. Pleasant Street
Amherst, MA 01003

work #: 413-325-6555
email: sakrejda@umass.edu

2015-09-14 16:57 GMT-04:00 bgoodri notifications@github.com:

**Comment by bgoodri** [comment]
I think I get it, but I'm kind of wondering what would be the most useful thing for a user. Currently, I have this test, which is based on the Stan manual and is passing:

```
test_extract_sparse_parts <- function() {
  A <- rbind(
    c(19L, 27L,  0L,  0L),
    c( 0L,  0L,  0L,  0L),
    c( 0L,  0L,  0L, 52L),
    c(81L,  0L, 95L, 33L)
  )
  w <- c(19, 27, 52, 81, 95, 33)
  v <- c(1, 2, 4, 1, 3, 4)
  u <- c(1, 3, 3, 4, 7)
  parts <- rstan::extract_sparse_parts(A, type = "CSC")
  checkEquals(parts$w, w)
  checkEquals(parts$v, v)
  checkEquals(parts$u, u)

  parts <- rstan::extract_sparse_parts(t(A * 1.0))
  checkEquals(parts$w, w)
  checkEquals(parts$v, v)
  checkEquals(parts$u, u)

  parts <- rstan::extract_sparse_parts(Matrix::t(Matrix::Matrix(A)))
  checkEquals(parts$w, w)
  checkEquals(parts$v, v)
  checkEquals(parts$u, u)
}
```

But if I had that `A` matrix and wanted to use the CSR representation in a Stan program to use with `csr_matrix_times_vector`, I think I would expect `extract_sparse_parts(A, type = "CSR")` to just work, but it would yield the wrong thing.

**Comment by sakrejda** [comment]
I'm not seeing why it wouldn't work at the moment but it's late. It's way
too easy to get turned around with this.  It might be easier if you lay out
the interface you want for rstan, along with the tests you want to have
passing and the I just make them pass. Interested in doing that? Krzysztof

**Comment by bgoodri** [comment]
The tests are passing, and I think they are doing what you would expect. But I don't think it is what users would expect. Suppose you want to do `A * b` in a Stan program where `A` is the same as in the user manual, except call it as `csr_matrix_times_vector(m, n, w, v, u, b)`. If you call in R, `wvu <- extract_sparse_parts(A)`, then it would not be what the manual suggests it would be. To match the manual, you would have to either pass in `t(A)` or specify `type  = "CSC"`.

**Comment by bgoodri** [comment]
We need to figure this out tonight / tomorrow morning or else wait to introduce the R function until the next minor rstan release.

**Comment by sakrejda** [comment]
Either way is fine with me.  My suggestion is that we should define what
the user-facing function is and make things go right from there. I think
the only problem is figuring out exactly where the extra transpose goes.  I
won't have more time tonight, but if you set up the tests so that they
define the desired UI (which should make them fail with the current version
of the function) I'm happy to make them work tomorrow morning.

2015-09-17 17:07 GMT-04:00 bgoodri notifications@github.com:

**Comment by bgoodri** [comment]
I think the R function should be (equivalent to)

```
extract_sparse_parts <- function(A) {
  stopifnot(length(dim(A)) == 2)
  An0 <- A != 0
  w <- c(t(A))
  w <- w[w != 0]
  v <- unlist(apply(An0, 1, which))
  u <- rowSums(An0)
  u <- cumsum(c(which(u > 0)[1], u))
  return(list(w = w, v = v, u = u))
}
```

This way if you have the matrix `A` from the manual

```
  A <- rbind(
    c(19L, 27L,  0L,  0L),
    c( 0L,  0L,  0L,  0L),
    c( 0L,  0L,  0L, 52L),
    c(81L,  0L, 95L, 33L)
  )
```

and a .stan function like

```
functions {
  vector test(int m, int n, vector w, int[] v, int[] u, vector b) {
    return csr_matrix_times_vector(m, n, w, v, u, b);
  }
}
model {}
```

and you call `expose_stan_functions()` on that .stan file and then in R do

```
b <- rnorm(ncol(A))
parts <- extract_sparse_parts(A)
as.matrix(test(nrow(A), ncol(A), parts$w, parts$v, parts$u, b))
```

you get

```
A %*% b
```

But the `extract_sparse_parts` function currently in the pull request does not achieve that behavior.

**Comment by sakrejda** [comment]
Ok, I'm going to simplify the function so it behaves as above.

**Comment by sakrejda** [comment]
Well, I see what's up now, I think  simplified function that does the transpose by default (the current 'CSC' option) will work fine, but rstan takes forever to reinstall and I'm out of time for the day so... unless you get a chance to do it I'll have to wait for the next release (I don' thave time to change it and I'm not going to push without testing).

**Comment by bgoodri** [comment]
You can push to the csr_extract branch. I can look at what you've done this afternoon.

**Comment by sakrejda** [comment]
I stuck around to test it: 

```
> library(rstan)
Loading required package: Rcpp
Loading required package: ggplot2
rstan (Version 2.7.0-4, packaged: 2015-09-18 19:11:32 UTC, GitRev: 05c3d0058b6a)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
>  A <- rbind(
+     c(19L, 27L,  0L,  0L),
+     c( 0L,  0L,  0L,  0L),
+     c( 0L,  0L,  0L, 52L),
+     c(81L,  0L, 95L, 33L)
+   )
> 
> expose_stan_functions('/tmp/test.stan')
> b <- rnorm(ncol(A))
> parts <- extract_sparse_parts(A)
> as.matrix(test(nrow(A), ncol(A), parts$w, parts$v, parts$u, b))
            [,1]
[1,]   -8.450245
[2,]    0.000000
[3,]  -59.492912
[4,] -265.790994
> A %*% b
            [,1]
[1,]   -8.450245
[2,]    0.000000
[3,]  -59.492912
[4,] -265.790994

```

**Pull request merged**
